language: node_js
node_js: node
services: mongodb
deploy:
  provider: heroku
  api_key:
    secure: Kf0n41JXri0L14mXdaQeM/faIzgg6rPVt5KkG3qy5eP/JLyxfcBw/w8IGtcpe7388ZfaL+ZoWrvb9BHKlkN9ILk3NO76NrSE2eoQ1P8bSqqFiU28hzrevvwQAMNUbDgRPdrgLVK+YDa+4pBmbObhcdOZ7k7XYSYtBGHdvO8El1pCkeAmdNufX5ws41GCrwLUERFY/unUe35UkMnTCXKwrtVzFSlWN4jV6lDlR+RAdPTDd+1xWCkFOQ+a3XcJIPiPDCwkundkOWrCx+9Ahqr2zl+zMTDZ4SMZ2hlmGySA1w1J8pXII6egkztyIfyaZ0eNpffG/fMn8tFUCQqUpNo0MQxs96HiZe3ThNnBj2Qci/CWkOdIPVVYmx2VRp48pxZmw+Vq0eKew8AqxgCqcPK3fXyW0tSZAMpkkKicTH2XlZkm+3jJtJdRrvT4nzgIMAY23siSeowDPwciSium23pY42ljRoG0plyztYGRsAjeRTCFti2GgZQB9pmPM8+/nv+j8gWKmeaUOy7Smn3RIyG6neNskaCNj2apMbZ+97Jh9RehvyRWcz6jvFpzpwMAvA2fCQzSZS41iUbP8WSASUduU8PKZuspJaHAfpkAmNV+TdkaCZrxUZ81nknRH3+1+22Fwva6ZD6hkkoMg6uqmJbl0P27JVex9C82yGhJmJ/hebs=
  app: guarded-peak-16645
  on:
    repo: alexjc1107/meal-repo
